spring:
  application:
    name: careercompass
  devtools:
    restart:
      enabled: true

  datasource:
    url: jdbc:mysql://sql5.freemysqlhosting.net:3306/sql5718974
    username: sql5718974
    password: FwiFsAsUmu

app:
  jwt:
    secret: Ft8!fWk2p$ueNxY6@7mV*Q9JzGbE5RDH&C\hjKL%PO^TrSw4dZv3c(qX)UsIaAg+B
    expiration:
      minutes: 30
  cors:
    allowed-origins: http://localhost:3000

logging:
  level:
    org.springframework.security: DEBUG
