spring:
  application:
    name: careercompass
  devtools:
    restart:
      enabled: true

  datasource:
    url: jdbc:mysql://sql3.freesqldatabase.com:3306/sql3697032
    username: sql3697032
    password: etGymg6EjA

app:
  jwt:
    secret: Ft8!fWk2p$ueNxY6@7mV*Q9JzGbE5RDH&C\hjKL%PO^TrSw4dZv3c(qX)UsIaAg+B
    expiration:
      minutes: 30
  cors:
    allowed-origins: http://localhost:3000

logging:
  level:
    org.springframework.security: DEBUG
